// Automatically generated by astro-icon
// a6b540a5b86d8ca6c33c8c1efb40b7137b5ec6658c5685b50223ed9fd57af232

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-down"
		| "arrow-left"
		| "arrow-right"
		| "arrow-up"
		| "author"
		| "facebook"
		| "hamburger"
		| "instagram"
		| "moon"
		| "nuxtjs"
		| "reading"
		| "sun"
		| "twitter"
		| "up-arrow"
		| "vuejs"
		| "youtube";
}